name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Unit Tests
        run: |
          echo "Build API"
          sleep 10s
      - name: Deploy to Render
        run: |
          echo "Build API"
          sleep 10s